export function getChatPageElements(doc = document) {
  return {
    startBtn: doc.getElementById("startBtn"),
    stopBtn: doc.getElementById("stopBtn"),
    statusDot: doc.getElementById("statusDot"),
    statusText: doc.getElementById("statusText"),
    versionText: doc.getElementById("versionText"),
    chatArea: doc.getElementById("chatArea"),
    surfaceDockShell: doc.getElementById("surfaceDockShell"),
    surfaceDockHost: doc.getElementById("surfaceDockHost"),
    surfaceDockResize: doc.getElementById("surfaceDockResize"),
    configBtn: doc.getElementById("configBtn"),
    surfaceSelect: doc.getElementById("surfaceSelect"),
    showMoreBtn: doc.getElementById("showMoreBtn"),
    configShell: doc.getElementById("configShell"),
    surfaceFloatRoot: doc.getElementById("surfaceFloatRoot"),
    debug: doc.getElementById("debug"),
    debugToggle: doc.getElementById("debugToggle"),
    debugPanel: doc.getElementById("debugPanel"),
    resizeHandle: doc.getElementById("resizeHandle"),
    userAvatarBtn: doc.getElementById("userAvatarBtn"),
    userMenu: doc.getElementById("userMenu"),
    userMenuName: doc.getElementById("userMenuName"),
    logoutBtn: doc.getElementById("logoutBtn"),
    sidebar: doc.getElementById("sidebar"),
    sidebarToggle: doc.getElementById("sidebarToggle"),
    currentProjectName: doc.getElementById("currentProjectName"),
    currentThreadName: doc.getElementById("currentThreadName"),
  };
}
